# Generated by Django 2.0.13 on 2021-06-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itpost',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='infotech/files'),
        ),
    ]
