# Generated by Django 2.0.13 on 2021-05-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linux', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linuximage',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='linux/images'),
        ),
    ]
