# Generated by Django 2.0.13 on 2021-06-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyposts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonpost',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='python/files'),
        ),
    ]
